spring.application.name=ShuttleShadowAI
# DB Connection
spring.datasource.url=jdbc:postgresql://dpg-d249k8ili9vc73cgvks0-a.oregon-postgres.render.com/shuttleshadow
spring.datasource.username=shuttleshadow_user
spring.datasource.password=FSNoKdlB7Q1TVuA1K0PW0AXaFnospqfw
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Jackson configuration
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# Disable CSRF (since we're not using Spring Security)
spring.mvc.hiddenmethod.filter.enabled=true

# Logging
logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always

# Connection pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
